## Spring
spring:
  profiles:
    active: default
    include: infrastructure
  boot:
    admin:
      discovery:
        ignored-services: spring-boot-admin
        enabled: true
        converter:
          health-endpoint-path: /manage
          management-context-path: /manage
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  security:
    user:
      name: user
      password: '{cipher}b90b4efc95fe1b35d1cdc0ee5a9297c759bbfe33ef798160a58a160de557f394'
      roles: USER

## Security
security:
  user:
    username: user
    password: '{cipher}b90b4efc95fe1b35d1cdc0ee5a9297c759bbfe33ef798160a58a160de557f394'
  basic:
    enabled: false
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /manage

## Server
server:
  port: 8081

## Info
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: log/
  level.root: warn


# Management
management:
  info:
     git:
       mode: full
  health:
    refresh:
      enabled: true
  endpoints:
    web:
      base-path: /manage
